apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: apps
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker.io/shymaa145/spring-boot-app
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: argocd

spec:
  type: NodePort
  selector:
    app: spring-boot-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
